### ISSUE TITLE
CPE responses?

### ISSUE THREAD

**Issue by P-T-I** [fkie-cad/nvd-json-data-feeds#5]
Are you planning to also cache the CPE responses?

**Comment by rhelmke** [comment]
Hello again,

we already fetch the complete CPE data and use it in a project that is not public (yet). We already discussed internally about a public feed similar to this repository. At the moment, there are few human resources we can allocate here. But that might change as early as Q1 2024. :-)

I will re-open this issue once there is any update on this matter. Thanks!

**Comment by P-T-I** [comment]
Good to hear; If I can help in some form, please let me know!
